# env: the system of your PC (e.g. windows, macOS, Linux)
env: macOS

# system: the target harmonyOS
system: android
# system: harmonyOS

device: emulator-5554
app_path: example/omninotes.apk
policy: guided
count: 100
properties: 
#  - example/example.py
  - example/example_mainpath_property.py
